### ISSUE TITLE
3D real forward out-of-place transform with sizes 98, 98, 98 fails with HIPFFT_EXEC_FAILED

### ISSUE THREAD

**Issue by ex-rzr** [ROCmSoftwarePlatform/hipFFT#26]
### What is the expected behavior
It should work, other sizes close to this one, as well as in-place transform seem to work ok.

### What actually happens

One of OpenMM-HIP tests fails:
https://github.com/StreamHPC/openmm-hip/issues/1
https://github.com/StreamHPC/openmm-hip/blob/master/platforms/hip/tests/TestHipFFTImplHipFFT.cpp#L144

### How to reproduce

```
./hipfft-rider -o -t 2 --length 98 98 98
```

```
Running profile with 1 samples
out-of-place
length: 98 98 98
terminate called after throwing an instance of 'std::runtime_error'
  what():  Execution failed
Aborted (core dumped)

```

### Environment
| Hardware | description |
|-----|-----|
| GPU | MI100, MI210, RX6900XT, does not depend on the GPU model |

| Software | version |
|-----|-----|
| ROCm | 5.2 |

**Comment by evetsso** [comment]
The problem here is actually in rocFFT, and has been fixed with https://github.com/ROCmSoftwarePlatform/rocFFT/commit/ced7c1cd468ef8ed2c96752d7ff12b66f5c21c2c .
