### ISSUE TITLE
Is it possible to use hipFFT from native C code?

### ISSUE THREAD

**Issue by mszpindler** [ROCmSoftwarePlatform/hipFFT#4]
I am trying to hipify C code with intensive use of C99 complex types. Translation from cuFFT to hipFFT makes trouble because of `#include <cstddef>` in `hipfft.h`.

**Comment by feizheng10** [comment]
Could you have a try with db92c2bb317d5c1c4857b17770f4aafb58d01726 ?

**Comment by malcolmroberts** [comment]
The clients can be compiled using g++, with either rocFFT or cuFFT backend.  There were some fixes in 32bd5a4 which fix how cmake handles this, but everything should be working now.

**Comment by malcolmroberts** [comment]
Correction: the commit is 894ea5c
