### ISSUE TITLE
Allow -fPIC as build option alongside -DBUILD_SHARED_LIBRARY=OFF

### ISSUE THREAD

**Issue by torrance** [ROCmSoftwarePlatform/hipFFT#44]
In a project I am currently hipifying first to the existing CUDA backend and then to AMD, there is extensive use of FFT callbacks.

This requires hipFFT be built as a static library (which, btw, needs to be more clearly documented).

However, in this case, the project is distributed as a portable library used by python, and so requires the static `hipfft.a` to be built with `-fPIC`.

At present, there is no way to specify as part of the CMake options that I want `-fPIC` passed as a compile flag. It would be great is this could be added as an option.

**Comment by evetsso** [comment]
Hi @torrance, are you able to use `-DCMAKE_CXX_FLAGS=-fPIC` to solve your immediate problem?

I'm a bit surprised to hear you mention callbacks - I haven't heard of many people using them, which is partly why the documentation on that end might be lacking.

If you don't mind, would you be able to describe your use case for callbacks?

In rocFFT, callbacks should be functional, but at this point I would not expect good performance out of them.  But depending on what it is that you're trying to do, I'm hoping there is (or will be) a better way to do it once you get to running on AMD hardware.

**Comment by torrance** [comment]
> Hi @torrance, are you able to use -DCMAKE_CXX_FLAGS=-fPIC to solve your immediate problem?

Yes, easy thank you - that worked!

> If you don't mind, would you be able to describe your use case for callbacks?

To be clear, this is a codebase that I'm porting, but was not the author. At present, however, it seems the call-backs are being used to efficiently perform an `fftshift` prior to the fft, depending on the direction. It does this by doing a both offset load and then applying a phase shift on the input array.

I think this could also be done as a kernel but this would have to be called separately and AIUI, the callback is the fastest method on CUDA.

**Comment by evetsso** [comment]
> At present, however, it seems the call-backs are being used to efficiently perform an `fftshift` prior to the fft, depending on the direction. It does this by doing a both offset load and then applying a phase shift on the input array.

Ok, that's helpful.  Do you know if you're doing exactly what `numpy.fft.fftshift` would do?  i.e. shifting the zero-frequency component to the centre of the spectrum?  Or are you shifting by a different amount?  Are you shifting multiple axes or just one?

Can you describe how the direction affects the shift?

I hope you don't mind all the questions - we're working on some changes to make this kind of computation easier and more efficient, and I'd really like to make sure we cover your whole use case.

> I think this could also be done as a kernel but this would have to be called separately and AIUI, the callback is the fastest method on CUDA.

Right, this makes sense.  I'm concerned that on AMD hardware the separate kernel may actually be faster until we finish the changes I mentioned.  You might need to test both to see what works best for you until that time.

**Comment by torrance** [comment]
> Do you know if you're doing exactly what numpy.fft.fftshift would do? i.e. shifting the zero-frequency component to the centre of the spectrum? Or are you shifting by a different amount? Are you shifting multiple axes or just one?

It's identical to what numpy's fftshift and ifftshift do - they're both essentially a circular shift along one or more axes. Those axes are the same axes that you are performing the fft on, eg. its common to have a 3D array which you perform the fft against just 2 of those axes, and you'd want to fftshift on those same two axes to return the zero-frequency to the centre of each 2D array slice.

(For reference, this need to centre the zero frequency is typical for radio astronomy as standard ordering is not physical in our domain.)

> Can you describe how the direction affects the shift?

This only matters in the case when performing and fftshift with odd dimensions. See numpy's fftshift versus ifftshift for clarification there.

I'll also add that another common use of the callback is to perform some kind of normalisation to the fft either during the load or after the fft has been done.

> Right, this makes sense. I'm concerned that on AMD hardware the separate kernel may actually be faster until we finish the changes I mentioned. You might need to test both to see what works best for you until that time.

Thank you, I'll keep this in mind! :)

**Comment by evetsso** [comment]
Thank you for your answers.  It sounds like we will be covering your use cases around shifts in a future release.

> I'll also add that another common use of the callback is to perform some kind of normalisation to the fft either during the load or after the fft has been done.

If this is something you need, hipFFT and rocFFT in ROCm 5.4 have APIs to do this efficiently without needing to use callbacks.  See `hipfftExtPlanScaleFactor` in hipfft.h and [rocfft_plan_description_set_scale_factor](https://rocmdocs.amd.com/projects/rocFFT/en/develop/index.html#result-scaling) in rocfft.h.  (And yes, this again highlights that hipFFT's documentation has some catching up to do - it's on the todo list!)

Also note that this will only work in hipFFT when using rocFFT as the backend library, since cuFFT does not directly support result scaling.

Since we seem to have gone well beyond solving your original problem, I'm closing this issue.  Please feel free to open additional issues if you run into any problems.

**Comment by malcolmroberts** [comment]
@torrance  - would you be able to share the library and operations that you're working on?  Always interested in learning what users are doing!

**Comment by torrance** [comment]
Just spotted the replies here:

@evetsso Thanks for the heads-up regarding the normalisation API, however since this isn't also support by CUDA it's not something I can rely on.

@malcolmroberts Sure, the library is https://github.com/ledatelescope/bifrost Note I'm not an author, I'm just tasked to hipify it to run on a local HPC stack here (Setonix @ Pawsey Supercomputing Centre, if you're curious).
