### ISSUE TITLE
Do not use find_package(HIP/hip REQUIRED)

### ISSUE THREAD

**Issue by haampie** [ROCmSoftwarePlatform/hipFFT#5]
Same issue as https://github.com/ROCmSoftwarePlatform/hipSPARSE/issues/211. This package uses

[`find_package(hip REQUIRED)`](https://github.com/ROCmSoftwarePlatform/hipFFT/blob/develop/cmake/dependencies.cmake#L29) and [`find_package(HIP REQUIRED)`](https://github.com/ROCmSoftwarePlatform/hipFFT/blob/develop/cmake/dependencies.cmake#L31)

There is both a module `FindHIP.cmake` and a `hip-config.cmake` file, it's ambiguous because search is case-insensitive, so please specify whether it's the module or the config file explicitly, like `find_package(HIP MODULE REQUIRED)` or `find_package(hip REQUIRED CONFIG)`.

From the CMake docs:

> In all cases the <name> is treated as case-insensitive and corresponds to any of the names specified (<PackageName> or names given by NAMES).

> In Module mode, CMake searches for a file called Find<PackageName>.cmake. The file is first searched in the CMAKE_MODULE_PATH, then among the Find Modules provided by the CMake installation.

> If the MODULE option is not specified in the above signature, CMake first searches for the package using Module mode. Then, if the package is not found, it searches again using Config mode.

**Comment by malcolmroberts** [comment]
I agree; find hip shouldn't always be required.

**Comment by malcolmroberts** [comment]
This should be fixed in 32bd5a4.

**Comment by malcolmroberts** [comment]
Correction: the commit is 894ea5c.

**Comment by haampie** [comment]
There's still a `MODULE`'s missing in in `clients/rider/CMakeLists.txt` and ` cmake/dependencies.cmake` though
