### ISSUE TITLE
fft callback fails on ROCM backend when using non-float input array

### ISSUE THREAD

**Issue by torrance** [ROCmSoftwarePlatform/hipFFT#53]
### The usecase

I have a large array of `short* idata` that I want to perform an FFT on (output: `hipComplex* odata`).

CUDA allows the use of load callbacks to avoid copying and casting the input data to `*float` first. For example, the following callback works as expected:

```cpp
__device__ hipfftReal mycallback(void *data, size_t offset, void* callerInfo, void* sharedPtr) {
    return reinterpret_cast<short*>(data)[offset];
}
```

I can then attach the callback and run the fft as usual:

<details>
<summary>code snippet (click to expand)</summary>

```cpp
    size_t n {2048};
    short* idata {};
    hipMallocManaged(reinterpret_cast<void**>(&idata), n * sizeof(short));

    for (size_t i = 0; i < n; ++i) {
        idata[i] = 1;
    }

    hipComplex* odata {};
    hipMallocManaged(reinterpret_cast<void**>(&odata), n * sizeof(hipComplex));

    hipfftHandle plan;
    hipfftPlan1d(&plan, n, HIPFFT_R2C, 1);

    hipfftCallbackLoadR mycallbackptr_h;
    hipMemcpyFromSymbol(&mycallbackptr_h, HIP_SYMBOL(mycallbackptr_d), sizeof(hipfftCallbackLoadR));

    hipfftXtSetCallback(plan, (void**) &mycallbackptr_h, HIPFFT_CB_LD_REAL, 0);
    hipfftExecR2C(plan, reinterpret_cast<float*>(idata), odata);
```
</details>

### What is the expected behavior

I expect the fft to perform as per usual, and not care where the data actually comes from, so long as the callback returns a valid `float` value.

This also works with other input `idata` types (the codebase I'm porting uses these for int8/char, int16/short, their unsigned equivalents, as well as their complex counterparts).

### What actually happens

On CUDA with hipfft, this works as expected.

On ROCM backend, it _almost_ works. For small memory allocations (nx = ~1000) this seems to work most of the time. For larger memory allocations, it fails with a `Memory access fault`, suggesting that despite my callback, the fft kernel is still trying to directly access the underlying array. And it works if I over allocate the `short* data` array, which backs up this hypothesis.

### How to reproduce

See the attached code snippet and callback.

### Environment
| Hardware | description |
|-----|-----|
| GPU | Radeon W6800 (0x73a3) |
| CPU | AMD Ryzen 5 5600 |

| Software | version |
|-----|-----|
| rofft | 5.5.0 |
| hipfft | 5.5.0 |

**Comment by malcolmroberts** [comment]
Thanks for reporting this; definitely an important use case that we may not have covered correctly.  We will look into this.

**Comment by evetsso** [comment]
Hi @torrance, in example you pasted the callback only does a type conversion.

In your actual code base, does your callback do anything else besides convert?

**Comment by torrance** [comment]
Hi @evetsso

As per https://github.com/ROCmSoftwarePlatform/hipFFT/issues/44, you can see I've described how elsewhere in the codebase callbacks are being used for normalisation and fftshift, in addition to type conversion as described here.

The codebase may do one or all of these things depending on flags passed.

**Comment by malcolmroberts** [comment]
Hey, @torrance; we are looking into solutions for your use case, but it'll probably take a little time.  We'll try and update with a patch that you can try before we commit to a release.

The issue that you're having is that we use the input buffer as a work buffer in real-to-complex transforms, thus overwriting the data.  Since your input buffer is allocated for shorts, it won't fit the floats that rocFFT tries to store there.  A temporary workaround for your code would be to allocate an input buffer large enough to accommodate the float data. This would still destroy the input, but you'd be able to run the FFT, using the callback, without issue.

**Comment by evetsso** [comment]
Hi @torrance, can I confirm whether you're doing this same kind of casting for complex-to-real input?  It sounds like this wouldn't be guaranteed to work in cuFFT without the same workaround mentioned by @malcolmroberts (i.e. allocate enough space in the input buffer for floats, even if it really only contains shorts).  [cuFFT's docs](https://docs.nvidia.com/cuda/cufft/index.html#data-layout) describe how complex-to-real input is overwritten.

**Comment by torrance** [comment]
@evetsso In our case we're only ever using the callbacks to allow: 1) integer inputs to be cast to float 'on the fly' prior to a R2C or D2Z transform 2) to perform an fftshift by multiplying by a checkerboard of +1 and -1.

**Comment by torrance** [comment]
@evetsso I will say that while the temporary workaround to allocate extra space in the input array does work, it results in significantly increased memory use that we had the intention to avoid by using low precision integers in the first place.

**Comment by evetsso** [comment]
This is fixed now with https://github.com/ROCmSoftwarePlatform/rocFFT/commit/e941031dee2ec526df5158bbfbe5d7a3e2f125b7 .

It will be included in an upcoming release.  If you need the fix sooner you would need to build rocFFT from source code.
